// let x = 5; console.log( x++ );
// console.log([ ] + false - null + true);
let y = 1; let x = y = 2; 
console.log(x);
// alert(x); 
console.log(typeof([ ] + 1 + 2) );
console.log("1"[0]);
console.log(2 && 1 && null && 0 && undefined);
let a=1, b=2;
console.log(!!( a && b ));
console.log(( a && b ));
console.log(( null || 2 && 3 || 4 ));
a = [1, 2, 3]; b = [1, 2, 3]; console.log(a == b);
console.log(typeof( +"Infinity" ));
console.log( 0 || "" || 2 || undefined || true || falsе );